/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardClassifyRouteImport } from './routes/dashboard.classify'
import { Route as DashboardDetectRouteImport } from './routes/dashboard.detect'
import { Route as DashboardPredictRouteImport } from './routes/dashboard.predict'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardCyclonesIndexRouteImport } from './routes/dashboard.cyclones.index'
import { Route as DashboardCyclonesIdRouteImport } from './routes/dashboard.cyclones.$id'
import { Route as DashboardHistoryIndexRouteImport } from './routes/dashboard.history.index'
import { Route as DashboardHistoryIdRouteImport } from './routes/dashboard.history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassifyRoute = DashboardClassifyRouteImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDetectRoute = DashboardDetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictRoute = DashboardPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCyclonesIndexRoute = DashboardCyclonesIndexRouteImport.update({
  id: '/cyclones/',
  path: '/cyclones/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCyclonesIdRoute = DashboardCyclonesIdRouteImport.update({
  id: '/cyclones/$id',
  path: '/cyclones/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryIndexRoute = DashboardHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryIdRoute = DashboardHistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/technology': typeof TechnologyRoute
  '/dashboard/classify': typeof DashboardClassifyRoute
  '/dashboard/detect': typeof DashboardDetectRoute
  '/dashboard/predict': typeof DashboardPredictRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cyclones/$id': typeof DashboardCyclonesIdRoute
  '/dashboard/history/$id': typeof DashboardHistoryIdRoute
  '/dashboard/cyclones/': typeof DashboardCyclonesIndexRoute
  '/dashboard/history/': typeof DashboardHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/technology': typeof TechnologyRoute
  '/dashboard/classify': typeof DashboardClassifyRoute
  '/dashboard/detect': typeof DashboardDetectRoute
  '/dashboard/predict': typeof DashboardPredictRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cyclones/$id': typeof DashboardCyclonesIdRoute
  '/dashboard/history/$id': typeof DashboardHistoryIdRoute
  '/dashboard/cyclones': typeof DashboardCyclonesIndexRoute
  '/dashboard/history': typeof DashboardHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/technology': typeof TechnologyRoute
  '/dashboard/classify': typeof DashboardClassifyRoute
  '/dashboard/detect': typeof DashboardDetectRoute
  '/dashboard/predict': typeof DashboardPredictRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cyclones/$id': typeof DashboardCyclonesIdRoute
  '/dashboard/history/$id': typeof DashboardHistoryIdRoute
  '/dashboard/cyclones/': typeof DashboardCyclonesIndexRoute
  '/dashboard/history/': typeof DashboardHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/technology'
    | '/dashboard/classify'
    | '/dashboard/detect'
    | '/dashboard/predict'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/cyclones/$id'
    | '/dashboard/history/$id'
    | '/dashboard/cyclones/'
    | '/dashboard/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/technology'
    | '/dashboard/classify'
    | '/dashboard/detect'
    | '/dashboard/predict'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/cyclones/$id'
    | '/dashboard/history/$id'
    | '/dashboard/cyclones'
    | '/dashboard/history'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/technology'
    | '/dashboard/classify'
    | '/dashboard/detect'
    | '/dashboard/predict'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/cyclones/$id'
    | '/dashboard/history/$id'
    | '/dashboard/cyclones/'
    | '/dashboard/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classify': {
      id: '/dashboard/classify'
      path: '/classify'
      fullPath: '/dashboard/classify'
      preLoaderRoute: typeof DashboardClassifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/detect': {
      id: '/dashboard/detect'
      path: '/detect'
      fullPath: '/dashboard/detect'
      preLoaderRoute: typeof DashboardDetectRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/predict': {
      id: '/dashboard/predict'
      path: '/predict'
      fullPath: '/dashboard/predict'
      preLoaderRoute: typeof DashboardPredictRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cyclones/': {
      id: '/dashboard/cyclones/'
      path: '/cyclones'
      fullPath: '/dashboard/cyclones/'
      preLoaderRoute: typeof DashboardCyclonesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cyclones/$id': {
      id: '/dashboard/cyclones/$id'
      path: '/cyclones/$id'
      fullPath: '/dashboard/cyclones/$id'
      preLoaderRoute: typeof DashboardCyclonesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history/': {
      id: '/dashboard/history/'
      path: '/history'
      fullPath: '/dashboard/history/'
      preLoaderRoute: typeof DashboardHistoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history/$id': {
      id: '/dashboard/history/$id'
      path: '/history/$id'
      fullPath: '/dashboard/history/$id'
      preLoaderRoute: typeof DashboardHistoryIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClassifyRoute: typeof DashboardClassifyRoute
  DashboardDetectRoute: typeof DashboardDetectRoute
  DashboardPredictRoute: typeof DashboardPredictRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCyclonesIdRoute: typeof DashboardCyclonesIdRoute
  DashboardHistoryIdRoute: typeof DashboardHistoryIdRoute
  DashboardCyclonesIndexRoute: typeof DashboardCyclonesIndexRoute
  DashboardHistoryIndexRoute: typeof DashboardHistoryIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClassifyRoute: DashboardClassifyRoute,
  DashboardDetectRoute: DashboardDetectRoute,
  DashboardPredictRoute: DashboardPredictRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCyclonesIdRoute: DashboardCyclonesIdRoute,
  DashboardHistoryIdRoute: DashboardHistoryIdRoute,
  DashboardCyclonesIndexRoute: DashboardCyclonesIndexRoute,
  DashboardHistoryIndexRoute: DashboardHistoryIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
